# build release

labels:
  platform: linux/amd64
    
steps:
  compile:
    when:
      event: [manual]
    image: alpine:latest
    commands:
      - apk update
      - apk add --no-cache bash build-base words-en gdb perl pcre2 pcre2-dev gdbm gdbm-dev pkgconfig meson ninja
      - meson setup --reconfigure --prefer-static build
      - ninja -C build
      - file build/dbtool
      - mv build/dbtool dbtool-linux-amd64

  release:
    image: alpine:latest
    when:
      event: [manual]
    environment:
      DEPLOY_TOKEN:
        from_secret: DEPLOY_TOKEN
    commands:
      - apk update
      - apk add --no-cache bash httpie jq git
      - .woodpecker/release.sh dbtool-linux-amd64
